﻿version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mengly123123/web-api1:latest
    container_name: web-api1-con
    ports:
      - 7770:80
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: Mengly@123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
